name: Scrape re3data

on:
  # We run this once a month
  schedule:
    - cron: '0 0 1 * *'

  # as well as upon manual triggers through the 'Actions' tab of the Github UI
  workflow_dispatch:

jobs:
  update:
    name: Scrape re3data and update the repository
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # setuptools_scm requires a non-shallow clone of the repository
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Python package
      run: |
        python -m pip install .[update]

    - name: Run update mechanism
      run: |
        scrape_re3data

    - uses: EndBug/add-and-commit@v9
      with:
        add: "./pooch_repositories/data/re3data_software.json"
        author_name: "Re3data Update Bot"
        message: "Update Re3data data"
